Map<String, String> tr = {
  "email": "email",
  "password": "şifre",
  "passwordConfirm": "şifre tekrar",
  "login": "Giriş yap",
  "register": "Kaydol.",
  "noAccount?": "Hesabın yok mu?",
  "privacyPolicy": "Gizlilik Politikası",
  "forgotPassword?": "Şifreni mi unuttun?",
  "phone": "telefon",
  "termsOfUse": "Kullanım sözleşmesini",
  "IAccept": "kabul ediyorum",
  "balance": "Bakiye",
  "addInstaAccount": "Hesap ekle",
  "username": "Kullanıcı adı",
  "add": "Ekle",
  "instaAccounts": "İnstagram hesaplarım",
  "products": "Ürünler",
  "account": "Hesap",
  "earningTable": "Kazanç tablosu",
  "punishments": "Cezalar",
  "settings": "Ayarlar",
  "mostEarnings": "En çok kazananlar",
  "name": "İsim",
  "lastName": "Soyisim",
  "birth_date": "Doğum tarihi",
  "basicInfo": "Temel bilgiler",
  "paymentInfo": "Ödeme bilgileri",
  "iban": "IBAN",
  "bank": "Banka",
  "save": "Kaydet",
  "appLanguage": "Uygulama dili",
  "moneyUnit": "Para birimi",
  "tr": "Türkçe",
  "en": "İngilizce",
  "fl": "Flemenkçe",
  "addInstagramAccountToStart":
      "Kazanmaya başlamak için bir instagram hesabı bağla",
  "termsShouldBeAccepted": "Kullanım koşullarını kabul etmediniz!",
  "passwordsNotEqual": "Şifreler eşleşmiyor!",
  "somethingWentWrong": "Bir şeyler ters gitti!",
  "fieldsEmpty": "Bilgiler boş bırakılamaz",
  "wrongPassword": "Şifre yanlış",
  "userNotFound": "Kullanıcı bulunamadı",
  "logOut": "Çıkış yap",
  "resetPassword": "Şifre sıfırla",
  "enterMailForReset":
      "Şifresini sıfırlamak istediğin hesabın mailini gir. Eğer böyle bir hesap varsa şifre sıfırlama bağlantısını göndereceğiz.",
  "send": "Gönder",
  "passwordResetSent": "Şifre sıfırlama bağlantısı gönderildi.",
  "invalidIBAN": "Geçersiz IBAN",
  "instaAccountAdded": "Instagram hesabı eklendi",
  "instaAccountAdFail": "Instagram hesabı eklenemedi.",
};
