Map<String, Map<String, String>> interactionStrings = {
  "tr": {
    "follow": "Takip",
    "usersToFollow":"Takip edilecek hesap",
    "postLikes": "Gönderi beğeni",
    "postSaves": "Gönderi kaydetme",
    "postComments": "Gönderi yorum",
    "commentLikes": "Yorum beğeni",
    "reelsLikes": "Reels beğeni",
    "reelsComment": "Reels yorum",
    "igtvLike": "IGTV Beğeni",
    "igtvComment": "IGTV yorum",
    "postShare": "Gönderi paylaşımı",
    "videoShares": "Video paylaşımı",
    "storyShare": "Hikaye paylaşımı",
    "singleUserDMs": "DM (Tekli)",
    "multiUserDMs": "DM (Çoklu)",
    "liveBroadCastLikes": "Canlı yayın beğeni",
    "liveBroadCastComments": "Canlı yayın yorum",
    "postSpam": "Gönderi spam",
    "userFradulentSpam": "Dolandırıcı hesap spam",
    "userSpam": "Hesap spam",
    "buy_item": "{item} satın alım",
    "like": "Beğeni",
    "comment": "Yorum",
    "message": "Mesaj",
    "refund": "İade",
    "pending": "Bekliyor",
    "completed": "Tamamlandı",
    "failed": "Başarısız",
    "spam": "Spam",
    "suicideSpam":"İntihar spam",
    "liveWatches": "Canlı yayın izlenme",
    "internetUsage1GB": "1GB internet kullanımı",
    "advertImageShare":"Reklam resmi paylaşma",
    "advertVideoShare": "Reklam video paylaşma",  
    "followerCount":"Takipçi sayısı",

  },
  "en": {
    "follow": "Follow",
    "usersToFollow": "Users to follow",
    "postLikes": "Post like",
    "postSaves": "Post save",
    "postComments": "Post comment",
    "commentLikes": "Comment like",
    "reelsLike": "Reels like",
    "reelsComment": "Reels comment",
    "igtvLike": "IGTV like",
    "igtvComment": "IGTV comment",
    "postShare": "Post share",
    "videoShares": "Video share",
    "storyShare": "Story share",
    "multiUserDMs": "Direct message (Multi)",
    "singleUserDMs": "Direct message (Single)",
    "liveBroadCastLikes": "Live broadcast like",
    "liveBroadCastComments": "Live broadcast comment",
    "postSpam": "Post spam",
    "userFradulentSpam": "Fradulent account spam",
    "userSpam": "Account spam",
    "buy_item": "Buy {item}",
    "like": "Like",
    "comment": "Comment",
    "message": "Message",
    "refund": "Refund",
    "pending": "Pending",
    "completed": "Completed",
    "failed": "Failed",
    "spam": "Spam",
    "suicideSpam": "Suicide Spam",
    "liveWatches": "Live watch",
    "internetUsage1GB":"1GB internet usage",
    "advertImageShare":"Share advert image",
    "advertVideoShare":"Share advert video",
    "followerCount":"Follower number"  

  }
};
