Map<String, Map<String, String>> interactionStrings = {
  "tr": {
    "follow": "Takip",
    "userToFollow":"Takip edilecek hesap",
    "postLikes": "Gönderi beğeni",
    "postSaves": "Gönderi kaydetme",
    "postComments": "Gönderi yorum",
    "commentLikes": "Yorum beğeni",
    "reelsLikes": "Reels beğeni",
    "reelsComment": "Reels yorum",
    "igtvLike": "IGTV Beğeni",
    "igtvComment": "IGTV yorum",
    "postShare": "Gönderi paylaşımı",
    "videoShare": "Video paylaşımı",
    "storyShare": "Hikaye paylaşımı",
    "singleUserDM": "DM (Tekli)",
    "multiUserDM": "DM (Çoklu)",
    "liveLike": "Canlı yayın beğeni",
    "liveComment": "Canlı yayın yorum",
    "postSpam": "Gönderi spam",
    "userFradulentSpam": "Dolandırıcı hesap spam",
    "userSpam": "Hesap spam",
    "buy_item": "{item} satın alım",
    "like": "Beğeni",
    "comment": "Yorum",
    "message": "Mesaj",
    "refund": "İade",
    "pending": "Bekliyor",
    "completed": "Tamamlandı",
    "failed": "Başarısız",
    "spam": "Spam",
    "suicideSpam":"İntihar spam",
    "liveWatch": "Canlı yayın izlenme"
  },
  "en": {
    "follow": "Follow",
    "userToFollow": "Users to follow",
    "postLikes": "Post like",
    "postSaves": "Post save",
    "postComments": "Post comment",
    "commentLikes": "Comment like",
    "reelsLike": "Reels like",
    "reelsComment": "Reels comment",
    "igtvLike": "IGTV like",
    "igtvComment": "IGTV comment",
    "postShare": "Post share",
    "videoShare": "Video share",
    "storyShare": "Story share",
    "multiUserDM": "Direct message (Multi)",
    "singleUserDM": "Direct message (Single)",
    "liveLike": "Live broadcast like",
    "liveComment": "Live broadcast comment",
    "postSpam": "Post spam",
    "userFradulentSpam": "Fradulent account spam",
    "userSpam": "Account spam",
    "buy_item": "Buy {item}",
    "like": "Like",
    "comment": "Comment",
    "message": "Message",
    "refund": "Refund",
    "pending": "Pending",
    "completed": "Completed",
    "failed": "Failed",
    "spam": "Spam",
    "suicideSpam": "Suicide Spam",
    "liveWatch": "Live watch"
  }
};
